namespace DirectoryAnalyzer
{
    internal static class TableOperator
    {
        private static int[] LongestElement(string[,] input)
        {
            var amountOfColumns = input.GetLength(1);
            var amountOfRows = input.GetLength(0);
            var setOfWidth = new int[amountOfColumns];

            for (int i = 0; i < amountOfColumns; i++)
            {
                var maxLength = 0;
                for (int j = 0; j < amountOfRows; j++)
                {
                    if ((input[j, i] ?? "").Length > maxLength)
                    {
                        maxLength = input[j, i].Length;
                    }
                }
                setOfWidth[i] = maxLength;
            }
            return setOfWidth;
        }

        internal static string[] BuildTable(string[,] input)
        {
            var amountOfRows = input.GetLength(0);
            var amountOfColumns = input.GetLength(1);
            var setOfColumnsWidth = LongestElement(input);


            var summarizedWidth = amountOfColumns * 3 + 1;
            //^amountOfColumns*3+1 is amount of additional symbols, generated by whitespaces before and
            //after text in cell plus vertical "lines" of table
            foreach (int localWidth in setOfColumnsWidth)
            {
                summarizedWidth += localWidth;
            }
            string horizontalLine = new('-', summarizedWidth);


            string[] answer = Enumerable.Repeat("", amountOfRows * 2 + 1).ToArray();
            //^additional rows in table was generated by horizontal lines
            for (int i = 0; i < amountOfRows * 2 + 1; i++)
            {
                if (i % 2 == 0)
                {
                    answer[i] = horizontalLine;
                }
                else
                {
                    answer[i] += "|";
                    for (int j = 0; j < amountOfColumns; j++)
                    {
                        answer[i] += " ";
                        answer[i] += input[i / 2, j];
                        var deltaLength = setOfColumnsWidth[j] - (input[i / 2, j] ?? "").Length;
                        for (uint k = 0; k < deltaLength; k++)
                        {
                            answer[i] += " ";
                        }
                        answer[i] += " |";
                    }
                }
            }
            return answer;
        }
    }
}
